# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class GriddoEnv < Formula
  desc ""
  homepage "https://github.com/danielrosse/env-generator"
  version "0.0.25"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/danielrosse/env-generator/releases/download/v0.0.25/env-generator_0.0.25_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "a701b8e4fb7521c6fa8930b55db7c580fcd9c7224da15e55680c7fd0bd36492d"

      def install
        bin.install "griddo-env"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/danielrosse/env-generator/releases/download/v0.0.25/env-generator_0.0.25_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fff125c065e6b18e61b71d5e38a3b510abe44be70ca997fc48be0e81553ffa53"

      def install
        bin.install "griddo-env"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/danielrosse/env-generator/releases/download/v0.0.25/env-generator_0.0.25_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d8cf8ea33780b34d3e12013b7f7bb10f5145cc464c95853246c21e0a964fe33e"

      def install
        bin.install "griddo-env"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielrosse/env-generator/releases/download/v0.0.25/env-generator_0.0.25_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "5a11cd73ff83bcd8944bae13b4fd1210b6cbb82f3b47d500d906fa78be55e5c8"

      def install
        bin.install "griddo-env"
      end
    end
  end
end
