# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GriddoEnv < Formula
  desc ""
  homepage "https://github.com/danielrosse/env-generator"
  version "0.0.10"

  on_macos do
    url "https://github.com/danielrosse/env-generator/releases/download/v0.0.10/env-generator_0.0.10_darwin_all.tar.gz"
    sha256 "d21b87fb0ce3f618254a7dadd2be355198fe11dda277ab036e03d3c71ffcac23"

    def install
      bin.install "griddo-env"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielrosse/env-generator/releases/download/v0.0.10/env-generator_0.0.10_linux_arm64.tar.gz"
      sha256 "0ba2274c37a4dd6e94b5c3524940272bbcbe81042fd4c38ebe792aa2c4cb8196"

      def install
        bin.install "griddo-env"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/danielrosse/env-generator/releases/download/v0.0.10/env-generator_0.0.10_linux_amd64.tar.gz"
      sha256 "a04188d6cad5c29924cce4b482a343aab7b8074be633ccd5fa00029343dfa3da"

      def install
        bin.install "griddo-env"
      end
    end
  end
end
