# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class GriddoEnv < Formula
  desc "Griddo env generator"
  homepage "https://github.com/danielrosse/env-generator"
  version "0.0.38"
  depends_on :macos

  on_macos do
    url "https://github.com/danielrosse/env-generator/releases/download/v0.0.38/env-generator_0.0.38_darwin_all.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "6fe04097b45d159d51ebab6e7b19767839f0e04699870ab60b54e4ee09c876b6"

    def install
      bin.install "griddo-env"
    end
  end
end
