# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ServerCx < Formula
  desc "Launch a local server for CX"
  homepage "https://github.com/danielrosse/InstanceServerCX"
  version "0.0.8"
  depends_on :macos

  url "https://github.com/danielrosse/InstanceServerCX/releases/download/v0.0.8/InstanceServerCX_0.0.8_darwin_all.tar.gz"
  sha256 "90ec80081f4a5f28304d3d9762589470748614fe3db98e292c404d8cfe009b94"

  def install
    bin.install "server-cx"
  end
end
