# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class ServerCx < Formula
  desc "Launch a local server for CX"
  homepage "https://github.com/danielrosse/InstanceServerCX"
  version "0.0.3"
  depends_on :macos

  on_macos do
    url "https://github.com/danielrosse/InstanceServerCX/releases/download/v0.0.3/InstanceServerCX_0.0.3_darwin_all.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "fde09b26ecdd4b233e2bdd688ae9c8edc248e94afe43a8ba549172e2ba39abfa"

    def install
      bin.install "server-cx"
    end
  end
end
