# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ServerCx < Formula
  desc "Launch a local server for CX"
  homepage "https://github.com/danielrosse/InstanceServerCX"
  version "0.0.4"
  depends_on :macos

  on_macos do
    url "https://github.com/danielrosse/InstanceServerCX/releases/download/v0.0.4/InstanceServerCX_0.0.4_darwin_all.tar.gz"
    sha256 "c2a9f5dc2b2ff130c379c71e5aad5abd262458befe0aab19f296dd8ce8b0a4ca"

    def install
      bin.install "server-cx"
    end
  end
end
